### ISSUE TITLE
README is outdated (as R.Danny reached server limit)

### ISSUE THREAD

**Issue by averwhy** [Rapptz/RoboDanny#104]
Since Danny has no plans on verification (which is fair), the readme should be updated to reflect this

**Comment by Nicofisi** [comment]
Why is that the case?

**Comment by JDJGInc** [comment]
Danny doesn't want to give discord his info.

**Comment by Nicofisi** [comment]
Why close this without updating the README? Did you choose to get verified after all?

**Comment by JDJGInc** [comment]
look at the bot on discord.
danny got verified a second way.

**Comment by Nicofisi** [comment]
Oh. Oh! Cool 8)

A suspicious second way 👀
