### ISSUE TITLE
R.Danny should reply on tag create/edit/etc. to the demand message

### ISSUE THREAD

**Issue by Lcfvs** [Rapptz/RoboDanny#105]
Hi,

Actually, the bot confirms a create/update/... but it can be confusing if 2 users are on it during the same time.

e.g. https://discord.com/channels/172018499005317120/172254696101249024/829064159429787648

Is it possible to make it really responding on the demand message, please?

**Comment by bsrecker** [comment]
You mean that when using the make command and you have multiple people doing it at the same time it is confusing?

**Comment by Lcfvs** [comment]
Yeah, because the bot doens't **reply** to the user message, it just send a new message instead.
