### ISSUE TITLE
it says "ModuleNotFoundError: No module named 'discord'"

### ISSUE THREAD

**Issue by superJK92iscool** [Rapptz/RoboDanny#126]
When I run `py launcher.py db init` (I know that's not what it says in the README file but I am on windows) it gives this 
`Traceback (most recent call last):
  File "launcher.py", line 6, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'`

Please help me fix this

**Comment by superJK92iscool** [comment]
same whin I do `python  launcher.py db init`

**Comment by superJK92iscool** [comment]
I still need help with this

**Comment by superJK92iscool** [comment]
I fixed that issue but now I get this 
`Traceback (most recent call last):
  File "launcher.py", line 112, in init
    importlib.import_module(ext)
  File "C:\Users\super\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\meta.py", line 1, in <module>
    from discord.ext import commands, menus
ImportError: cannot import name 'menus' from 'discord.ext' (unknown location)`

**Comment by nxtlo** [comment]
just run `py -m pip install --user -U -r requirements.txt`

**Comment by superJK92iscool** [comment]
doing that gave me this

`    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\super\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize
; sys.argv[0] = '"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru-dict\\setup.py'"'"'; __file__='"'
"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru-dict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'
"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec
'"'"'))' install --record 'C:\Users\super\AppData\Local\Temp\pip-record-4ed10r4q\install-record.txt' --single-version-ex
ternally-managed --compile --user --prefix=
         cwd: C:\Users\super\AppData\Local\Temp\pip-install-_cm0n39z\lru-dict\
    Complete output (11 lines):
    running install
    running build
    running build_ext
    building 'lru' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /n
ologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\super\AppData\Local\Programs\Python\Python38\include -IC:\Users\super\AppData\
Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14
.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tclru.c /Fobuild\temp.win-amd64-3.
8\Release\lru.obj
    lru.c
    c:\users\super\appdata\local\programs\python\python38\include\pyconfig.h(59): fatal error C1083: Cannot open include
 file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin
\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\super\AppData\Local\Programs\Python\Python38\python.exe' -u -c
'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru-
dict\\setup.py'"'"'; __file__='"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru-dict\\setup.py'"'"'
;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(
compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\super\AppData\Local\Temp\pip-record-4ed10r4q\instal
l-record.txt' --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.`

**Comment by superJK92iscool** [comment]
@nxtlo 

> 
> 
> doing that gave me this
> 
> ` ERROR: Command errored out with exit status 1: command: 'C:\Users\super\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize ; sys.argv[0] = '"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru-dict\\setup.py'"'"'; __file__='"' "'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru-dict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"' "', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec '"'"'))' install --record 'C:\Users\super\AppData\Local\Temp\pip-record-4ed10r4q\install-record.txt' --single-version-ex ternally-managed --compile --user --prefix= cwd: C:\Users\super\AppData\Local\Temp\pip-install-_cm0n39z\lru-dict\ Complete output (11 lines): running install running build running build_ext building 'lru' extension creating build creating build\temp.win-amd64-3.8 creating build\temp.win-amd64-3.8\Release C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /n ologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\super\AppData\Local\Programs\Python\Python38\include -IC:\Users\super\AppData\ Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14 .16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tclru.c /Fobuild\temp.win-amd64-3. 8\Release\lru.obj lru.c c:\users\super\appdata\local\programs\python\python38\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin \\HostX86\\x64\\cl.exe' failed with exit status 2 ---------------------------------------- ERROR: Command errored out with exit status 1: 'C:\Users\super\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru- dict\\setup.py'"'"'; __file__='"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-_cm0n39z\\lru-dict\\setup.py'"'"' ;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec( compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\super\AppData\Local\Temp\pip-record-4ed10r4q\instal l-record.txt' --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.`

**Comment by superJK92iscool** [comment]
I fixed it but now it give
` Could not load cogs.meta.
Traceback (most recent call last):
  File "launcher.py", line 112, in init
    importlib.import_module(ext)
  File "C:\Users\super\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\meta.py", line 2, in <module>
    from .utils import checks, formats, time
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\utils\time.py", line 3, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'`

**Comment by nxtlo** [comment]
read the error, you need to install `dateutil` module.

**Comment by superJK92iscool** [comment]
I tried but it gives 
`  ERROR: Could not find a version that satisfies the requirement dateutil (from versions: none)
ERROR: No matching distribution found for dateutil`

**Comment by Rapptz** [comment]
This isn't really a place to get help with pip.

**Comment by superJK92iscool** [comment]
I fixit now when I run it I get
`Could not load cogs.meta.
Traceback (most recent call last):
  File "launcher.py", line 112, in init
    importlib.import_module(ext)
  File "C:\Users\super\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\meta.py", line 2, in <module>
    from .utils import checks, formats, time
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\utils\time.py", line 3, in <module>
    from dateutil.relativedelta import relativedelta
ValueError: source code string cannot contain null bytes` @nxtlo
