### ISSUE TITLE
A small enhancement to the token detection and GitHub-gist upload system

### ISSUE THREAD

**Issue by ImNimboss** [Rapptz/RoboDanny#134]
Currently when R.Danny detects a token in a message it creates a new gist, from which Discord can detect the token
But what if instead of creating a new gist it just edited the same gist over and over again so Discord could read from that?
That would be a lot cleaner, and maybe in the future you could create gists without them getting overcrowded by token gists

**Comment by Rapptz** [comment]
I don't really see much of a point. It's a bot account.
