### ISSUE TITLE
Set timezone slash command does not respond

### ISSUE THREAD

**Issue by LostLuma** [Rapptz/RoboDanny#164]
The `/timezone set` command seemingly leads to an internal error and causes the bot to not respond. Text variant works as expected.

![sadness](https://github.com/Rapptz/RoboDanny/assets/38926001/de769078-7efd-41d3-abab-b54042db629a)

**Comment by Rapptz** [comment]
Hm this looks like a d.py bug

**Comment by Rapptz** [comment]
Should be fixed now due to d.py bump.
