### ISSUE TITLE
starboard can log a message in a nsfw channel when the starboard channel isn't

### ISSUE THREAD

**Issue by nihaals** [Rapptz/RoboDanny#17]
Maybe check if `channel.nsfw and not starboard.nsfw`?

**Comment by khionu** [comment]
Wat

**Comment by modelmat** [comment]
I think it means that the starboard can show messages from an NSFW channel, when the Starboard channels isn't set to that/

**Comment by khionu** [comment]
Hmm.... might be a good idea to set this as default behavior, with a config override, to help with compliance to Discord's Community Guidelines.

**Comment by emptix0** [comment]
lol
