### ISSUE TITLE
Feature Request: Check if a user is still in guild before sending their reminders

### ISSUE THREAD

**Issue by aveao** [Rapptz/RoboDanny#26]
Someone who's not in our guild anymore just got a reminder from rdanny.

Obv he can't see it. 

Wouldn't it be better to check if they're in the guild or not before sending their reminder and either not sending the reminder or DMing the reminder?

**Comment by Rapptz** [comment]
I know it's weird but I actually kept the behaviour as-is because I kind of like it.
