### ISSUE TITLE
Starboard should include a quick link to the starred message

### ISSUE THREAD

**Issue by LikeLakers2** [Rapptz/RoboDanny#34]
Since Discord allows linking to specific messages using a link structured as `https://discordapp.com/channels/{server.id}/{channel.id}/{message.id}`, Danny should probably include that sort of link in the starboard message, to make it easier to get some context.

**Comment by holedaemon** [comment]
Danny has [said](https://discordapp.com/channels/182325885867786241/182328102167248896/475258691096936449) he intends to implement this, but is waiting until the URL works when masked in an embed.

**Comment by LikeLakers2** [comment]
I'm curious why he doesn't just put it in the message content for the time being then.

**Comment by mikeshardmind** [comment]
Just an FYI, the behavior of masked urls in embeds has been fixed.

Edit: nvm, apparently only in descriptions.

**Comment by Rapptz** [comment]
This has been implemented as of today. If your server wants to update the last ~1000 entries then you should use `?star migrate` to do so. I'll probably remove that command in a few weeks or so.
