### ISSUE TITLE
Starboard's Jump option isn't always accurate.

### ISSUE THREAD

**Issue by ManavRaja** [Rapptz/RoboDanny#67]
When I clicked jump on the Starboard this morning, the bot took me quite a bit above where the actual message was. I kept trying over & over again. I got inconsistent results, but most time, the jump was a bit off mark. It happened in the discord.py server. I have a pic of which one had the error.
![Capture](https://user-images.githubusercontent.com/61202382/82118473-4b478900-973d-11ea-8703-009a96271993.PNG)

**Comment by Rapptz** [comment]
No repro. Sounds like a client bug.

**Comment by ManavRaja** [comment]
Ah, Ok
