### ISSUE TITLE
a suggestion 

### ISSUE THREAD

**Issue by yuzarx** [Rapptz/RoboDanny#69]
a tags sorting for a specific user

**Comment by Rapptz** [comment]
I'm unsure what this means. Could you elaborate?

**Comment by yuzarx** [comment]
a tag sort by either rank or uses
instead of showing user tags randomly, list them sorted by uses or rank

**Comment by Rapptz** [comment]
Sorry for the late response.

I can't really add extra configuration parameters to `?tag list` since it already takes one positional argument, the member. The best I could do is add one to `?tag all` but this doesn't seem to be your feature request.
