### ISSUE TITLE
Banned from R. Danny

### ISSUE THREAD

**Issue by HeyItsSirius** [Rapptz/RoboDanny#71]
Good day,

So this happened a while back and I can't find any sort of support server so I came here. Quite a while back I believe I ended up blacklisting myself from the bot by using the ?star random command too much (my Discord handle is HeyItsSirius#0019). Just wasn't sure if I could get access to the bot again or what

**Comment by nxtlo** [comment]
there's a discord server for [R. Danny](https://discord.gg/9dFU9dW)
