### ISSUE TITLE
!translate issue

### ISSUE THREAD

**Issue by KajuKaVyapari** [Rapptz/RoboDanny#79]
running !translate {anything} returns An error occurred: AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Rapptz** [comment]
It's a problem with the dependency not really something I can control unfortunately.

**Comment by Motzumoto** [comment]
> It's a problem with the dependency not really something I can control unfortunately.

yeah that's what I assumed was the issue, thanks for replying

**Comment by bsrecker** [comment]
The latest release candidate for Googletrans (4.0.0rc1) seems to have addressed this issue.

**Comment by Motzumoto** [comment]
this still isnt fixed btw, rapptz said it was in a different closed thread but i just tried it and its still not working. same error:

`An error occurred: AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by Rapptz** [comment]
Works for me. I already updated the dependencies so anything that remains broken is the fault of the package still.
