### ISSUE TITLE
Export tags

### ISSUE THREAD

**Issue by OoLunar** [Rapptz/RoboDanny#83]
Hello!

Awhile back, members of The Coding Den asked for a way to export tags. This was implemented through `?tag all --text`, which uploads a parsable file containing the output of a `SELECT` query. However, I noticed that this doesn't include the content of the tags, meaning we can't export them directly to another bot, or to a JSON file. Is there a roadblock that's stopping this from happening?

**Comment by OoLunar** [comment]
![image](https://user-images.githubusercontent.com/46751150/101270421-90192880-373e-11eb-9922-b631a3890aab.png)
> I seldom accept PRs for the bot

Expect the cleanest, most efficient and well-documented PR. Seldom means rare, which means there's a chance.

**Comment by JDJGInc** [comment]
How about having json and sql (ie sqlite or sql file) exports as well?

**Comment by OoLunar** [comment]
JSON support was added in PR #93, though it was never merged. While I can certainly reopen the PR, I don't think it's going to be merged. Closing as not planned.
