### ISSUE TITLE
Translate command broken?

### ISSUE THREAD

**Issue by RMB-1** [Rapptz/RoboDanny#91]
![image](https://user-images.githubusercontent.com/56851158/108921465-3e6c9580-75eb-11eb-8789-77315172515b.png)

It's been doing that every time now

**Comment by volcanicer** [comment]
The translate command has been broken for a while due to an issue with the version of the googletrans library that is currently being used. There's another issue open at the moment regarding this issue (see #79).

**Comment by RMB-1** [comment]
> The translate command has been broken for a while due to an issue with the version of the googletrans library that is currently being used. There's another issue open at the moment regarding this issue (see #79). 

Oh thanks for letting me know

**Comment by bsrecker** [comment]
The translate command is not broken. Update the googletrans lib to the latest/dev version.

**Comment by Rapptz** [comment]
This should be fixed.
